namespace ClinicEMR.UserControls
{
    partial class PatientRecordControl
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        private void InitializeComponent()
        {
            lblPatientInfo = new Label();
            tblHeader = new TableLayoutPanel();
            cboPatient = new ComboBox();
            lblPatient = new Label();
            lblPatientName = new Label();
            labelMeta = new Label();
            lblAllergies = new Label();
            lblMeta = new Label();
            lblAllergy = new Label();
            tblLayout = new TableLayoutPanel();
            tableLayoutPanel1 = new TableLayoutPanel();
            tbPatientRecord = new TabControl();
            tabVitals = new TabPage();
            dgvVitals = new DataGridView();
            tabConsultations = new TabPage();
            dgvConsultations = new DataGridView();
            tabPrescriptions = new TabPage();
            dgvPrescriptions = new DataGridView();
            tabMedicalHistory = new TabPage();
            tableLayoutPanel2 = new TableLayoutPanel();
            tableLayoutPanel3 = new TableLayoutPanel();
            txtHxMeds = new TextBox();
            lblCurrMed = new Label();
            txtHxFamily = new TextBox();
            lblFamHis = new Label();
            lblSurgery = new Label();
            lblConditions = new Label();
            txtHxAllergies = new TextBox();
            label2 = new Label();
            txtHxConditions = new TextBox();
            txtHxSurgeries = new TextBox();
            btnEditHistory = new Button();
            btnPrint = new Button();
            tblHeader.SuspendLayout();
            tblLayout.SuspendLayout();
            tableLayoutPanel1.SuspendLayout();
            tbPatientRecord.SuspendLayout();
            tabVitals.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvVitals).BeginInit();
            tabConsultations.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvConsultations).BeginInit();
            tabPrescriptions.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dgvPrescriptions).BeginInit();
            tabMedicalHistory.SuspendLayout();
            tableLayoutPanel2.SuspendLayout();
            tableLayoutPanel3.SuspendLayout();
            SuspendLayout();
            lblPatientInfo.Anchor = AnchorStyles.Left;
            lblPatientInfo.AutoSize = true;
            lblPatientInfo.Location = new Point(3, 7);
            lblPatientInfo.Name = "lblPatientInfo";
            lblPatientInfo.Size = new Size(47, 15);
            lblPatientInfo.TabIndex = 0;
            lblPatientInfo.Text = "Patient:";
            tblHeader.ColumnCount = 3;
            tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
            tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 68F));
            tblHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            tblHeader.Controls.Add(cboPatient, 1, 0);
            tblHeader.Controls.Add(lblPatientInfo, 0, 0);
            tblHeader.Controls.Add(lblPatient, 0, 1);
            tblHeader.Controls.Add(lblPatientName, 1, 1);
            tblHeader.Controls.Add(labelMeta, 0, 2);
            tblHeader.Controls.Add(lblMeta, 1, 2);
            tblHeader.Controls.Add(lblAllergies, 0, 3);
            tblHeader.Controls.Add(lblAllergy, 1, 3);
            tblHeader.Controls.Add(btnPrint, 2, 0);
            tblHeader.Dock = DockStyle.Fill;
            tblHeader.Location = new Point(20, 20);
            tblHeader.Margin = new Padding(20, 20, 20, 3);
            tblHeader.Name = "tblHeader";
            tblHeader.RowCount = 4;
            tblHeader.RowStyles.Add(new RowStyle());
            tblHeader.RowStyles.Add(new RowStyle());
            tblHeader.RowStyles.Add(new RowStyle());
            tblHeader.RowStyles.Add(new RowStyle());
            tblHeader.Size = new Size(739, 117);
            tblHeader.TabIndex = 0;
            tblHeader.SetRowSpan(btnPrint, 4);
            cboPatient.Dock = DockStyle.Fill;
            cboPatient.DropDownStyle = ComboBoxStyle.DropDownList;
            cboPatient.FormattingEnabled = true;
            cboPatient.Location = new Point(106, 3);
            cboPatient.Name = "cboPatient";
            cboPatient.Size = new Size(630, 23);
            cboPatient.TabIndex = 1;
            cboPatient.SelectedIndexChanged += cboPatient_SelectedIndexChanged;
            lblPatient.AutoSize = true;
            lblPatient.Location = new Point(3, 29);
            lblPatient.Name = "lblPatient";
            lblPatient.Size = new Size(42, 15);
            lblPatient.TabIndex = 2;
            lblPatient.Text = "Name:";
            lblPatientName.AutoSize = true;
            lblPatientName.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblPatientName.Location = new Point(106, 29);
            lblPatientName.Name = "lblPatientName";
            lblPatientName.Size = new Size(0, 21);
            lblPatientName.TabIndex = 3;
            labelMeta.AutoSize = true;
            labelMeta.Location = new Point(3, 50);
            labelMeta.Name = "labelMeta";
            labelMeta.Size = new Size(42, 15);
            labelMeta.TabIndex = 4;
            labelMeta.Text = "Details:";
            lblAllergies.AutoSize = true;
            lblAllergies.Location = new Point(3, 65);
            lblAllergies.Name = "lblAllergies";
            lblAllergies.Size = new Size(66, 15);
            lblAllergies.TabIndex = 5;
            lblAllergies.Text = "Allergy/ies:";
            lblMeta.AutoSize = true;
            lblMeta.Location = new Point(106, 50);
            lblMeta.Name = "lblMeta";
            lblMeta.Size = new Size(0, 15);
            lblMeta.TabIndex = 6;
            lblAllergy.AutoSize = true;
            lblAllergy.Location = new Point(106, 65);
            lblAllergy.Name = "lblAllergy";
            lblAllergy.Size = new Size(0, 15);
            lblAllergy.TabIndex = 7;
            btnPrint.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnPrint.Location = new Point(621, 3);
            btnPrint.Name = "btnPrint";
            btnPrint.Size = new Size(115, 32);
            btnPrint.TabIndex = 8;
            btnPrint.Text = "Print Record";
            btnPrint.UseVisualStyleBackColor = true;
            btnPrint.Click += btnPrint_Click;
            tblLayout.ColumnCount = 1;
            tblLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tblLayout.Controls.Add(tblHeader, 0, 0);
            tblLayout.Controls.Add(tableLayoutPanel1, 0, 1);
            tblLayout.Dock = DockStyle.Fill;
            tblLayout.Location = new Point(0, 0);
            tblLayout.Name = "tblLayout";
            tblLayout.RowCount = 2;
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 140F));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tblLayout.Size = new Size(779, 592);
            tblLayout.TabIndex = 0;
            tableLayoutPanel1.ColumnCount = 1;
            tableLayoutPanel1.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tableLayoutPanel1.Controls.Add(tbPatientRecord, 0, 0);
            tableLayoutPanel1.Dock = DockStyle.Fill;
            tableLayoutPanel1.Location = new Point(20, 143);
            tableLayoutPanel1.Margin = new Padding(20, 3, 20, 20);
            tableLayoutPanel1.Name = "tableLayoutPanel1";
            tableLayoutPanel1.RowCount = 1;
            tableLayoutPanel1.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            tableLayoutPanel1.Size = new Size(739, 429);
            tableLayoutPanel1.TabIndex = 1;
            tbPatientRecord.Controls.Add(tabVitals);
            tbPatientRecord.Controls.Add(tabConsultations);
            tbPatientRecord.Controls.Add(tabPrescriptions);
            tbPatientRecord.Controls.Add(tabMedicalHistory);
            tbPatientRecord.Dock = DockStyle.Fill;
            tbPatientRecord.Location = new Point(3, 3);
            tbPatientRecord.Name = "tbPatientRecord";
            tbPatientRecord.SelectedIndex = 0;
            tbPatientRecord.Size = new Size(733, 423);
            tbPatientRecord.TabIndex = 0;
            tabVitals.Controls.Add(dgvVitals);
            tabVitals.Location = new Point(4, 24);
            tabVitals.Name = "tabVitals";
            tabVitals.Padding = new Padding(3);
            tabVitals.Size = new Size(725, 395);
            tabVitals.TabIndex = 0;
            tabVitals.Text = "Vitals";
            tabVitals.UseVisualStyleBackColor = true;
            dgvVitals.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvVitals.Dock = DockStyle.Fill;
            dgvVitals.Location = new Point(3, 3);
            dgvVitals.Name = "dgvVitals";
            dgvVitals.Size = new Size(719, 389);
            dgvVitals.TabIndex = 0;
            tabConsultations.Controls.Add(dgvConsultations);
            tabConsultations.Location = new Point(4, 24);
            tabConsultations.Name = "tabConsultations";
            tabConsultations.Padding = new Padding(3);
            tabConsultations.Size = new Size(725, 395);
            tabConsultations.TabIndex = 1;
            tabConsultations.Text = "Consultations";
            tabConsultations.UseVisualStyleBackColor = true;
            dgvConsultations.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvConsultations.Dock = DockStyle.Fill;
            dgvConsultations.Location = new Point(3, 3);
            dgvConsultations.Name = "dgvConsultations";
            dgvConsultations.Size = new Size(719, 389);
            dgvConsultations.TabIndex = 0;
            tabPrescriptions.Controls.Add(dgvPrescriptions);
            tabPrescriptions.Location = new Point(4, 24);
            tabPrescriptions.Name = "tabPrescriptions";
            tabPrescriptions.Padding = new Padding(3);
            tabPrescriptions.Size = new Size(725, 395);
            tabPrescriptions.TabIndex = 2;
            tabPrescriptions.Text = "Prescriptions";
            tabPrescriptions.UseVisualStyleBackColor = true;
            dgvPrescriptions.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dgvPrescriptions.Dock = DockStyle.Fill;
            dgvPrescriptions.Location = new Point(3, 3);
            dgvPrescriptions.Name = "dgvPrescriptions";
            dgvPrescriptions.Size = new Size(719, 389);
            dgvPrescriptions.TabIndex = 0;
            tabMedicalHistory.Controls.Add(tableLayoutPanel2);
            tabMedicalHistory.Location = new Point(4, 24);
            tabMedicalHistory.Name = "tabMedicalHistory";
            tabMedicalHistory.Padding = new Padding(3);
            tabMedicalHistory.Size = new Size(725, 395);
            tabMedicalHistory.TabIndex = 3;
            tabMedicalHistory.Text = "Medical History";
            tabMedicalHistory.UseVisualStyleBackColor = true;
            tableLayoutPanel2.ColumnCount = 1;
            tableLayoutPanel2.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            tableLayoutPanel2.Controls.Add(tableLayoutPanel3, 0, 0);
            tableLayoutPanel2.Controls.Add(btnEditHistory, 0, 1);
            tableLayoutPanel2.Dock = DockStyle.Fill;
            tableLayoutPanel2.Location = new Point(3, 3);
            tableLayoutPanel2.Name = "tableLayoutPanel2";
            tableLayoutPanel2.RowCount = 2;
            tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 86F));
            tableLayoutPanel2.RowStyles.Add(new RowStyle(SizeType.Percent, 14F));
            tableLayoutPanel2.Size = new Size(719, 389);
            tableLayoutPanel2.TabIndex = 0;
            tableLayoutPanel3.ColumnCount = 2;
            tableLayoutPanel3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            tableLayoutPanel3.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 75F));
            tableLayoutPanel3.Controls.Add(txtHxMeds, 1, 4);
            tableLayoutPanel3.Controls.Add(lblCurrMed, 0, 4);
            tableLayoutPanel3.Controls.Add(txtHxFamily, 1, 3);
            tableLayoutPanel3.Controls.Add(lblFamHis, 0, 3);
            tableLayoutPanel3.Controls.Add(lblSurgery, 0, 2);
            tableLayoutPanel3.Controls.Add(lblConditions, 0, 1);
            tableLayoutPanel3.Controls.Add(txtHxAllergies, 1, 0);
            tableLayoutPanel3.Controls.Add(label2, 0, 0);
            tableLayoutPanel3.Controls.Add(txtHxConditions, 1, 1);
            tableLayoutPanel3.Controls.Add(txtHxSurgeries, 1, 2);
            tableLayoutPanel3.Dock = DockStyle.Fill;
            tableLayoutPanel3.Location = new Point(3, 3);
            tableLayoutPanel3.Name = "tableLayoutPanel3";
            tableLayoutPanel3.RowCount = 5;
            tableLayoutPanel3.RowStyles.Add(new RowStyle());
            tableLayoutPanel3.RowStyles.Add(new RowStyle());
            tableLayoutPanel3.RowStyles.Add(new RowStyle());
            tableLayoutPanel3.RowStyles.Add(new RowStyle());
            tableLayoutPanel3.RowStyles.Add(new RowStyle());
            tableLayoutPanel3.Size = new Size(713, 328);
            tableLayoutPanel3.TabIndex = 0;
            txtHxMeds.Dock = DockStyle.Fill;
            txtHxMeds.Location = new Point(181, 119);
            txtHxMeds.Name = "txtHxMeds";
            txtHxMeds.Size = new Size(529, 23);
            txtHxMeds.TabIndex = 9;
            lblCurrMed.AutoSize = true;
            lblCurrMed.Location = new Point(3, 116);
            lblCurrMed.Name = "lblCurrMed";
            lblCurrMed.Size = new Size(123, 15);
            lblCurrMed.TabIndex = 8;
            lblCurrMed.Text = "Current Medication/s:";
            txtHxFamily.Dock = DockStyle.Fill;
            txtHxFamily.Location = new Point(181, 90);
            txtHxFamily.Name = "txtHxFamily";
            txtHxFamily.Size = new Size(529, 23);
            txtHxFamily.TabIndex = 7;
            lblFamHis.AutoSize = true;
            lblFamHis.Location = new Point(3, 87);
            lblFamHis.Name = "lblFamHis";
            lblFamHis.Size = new Size(83, 15);
            lblFamHis.TabIndex = 6;
            lblFamHis.Text = "Family History:";
            lblSurgery.AutoSize = true;
            lblSurgery.Location = new Point(3, 58);
            lblSurgery.Name = "lblSurgery";
            lblSurgery.Size = new Size(58, 15);
            lblSurgery.TabIndex = 5;
            lblSurgery.Text = "Surgeries:";
            lblConditions.AutoSize = true;
            lblConditions.Location = new Point(3, 29);
            lblConditions.Name = "lblConditions";
            lblConditions.Size = new Size(68, 15);
            lblConditions.TabIndex = 4;
            lblConditions.Text = "Conditions:";
            txtHxAllergies.Dock = DockStyle.Fill;
            txtHxAllergies.Location = new Point(181, 3);
            txtHxAllergies.Name = "txtHxAllergies";
            txtHxAllergies.Size = new Size(529, 23);
            txtHxAllergies.TabIndex = 1;
            label2.AutoSize = true;
            label2.Location = new Point(3, 0);
            label2.Name = "label2";
            label2.Size = new Size(66, 15);
            label2.TabIndex = 0;
            label2.Text = "Allergy/ies:";
            txtHxConditions.Dock = DockStyle.Fill;
            txtHxConditions.Location = new Point(181, 32);
            txtHxConditions.Name = "txtHxConditions";
            txtHxConditions.Size = new Size(529, 23);
            txtHxConditions.TabIndex = 2;
            txtHxSurgeries.Dock = DockStyle.Fill;
            txtHxSurgeries.Location = new Point(181, 61);
            txtHxSurgeries.Name = "txtHxSurgeries";
            txtHxSurgeries.Size = new Size(529, 23);
            txtHxSurgeries.TabIndex = 3;
            btnEditHistory.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            btnEditHistory.Location = new Point(596, 337);
            btnEditHistory.Name = "btnEditHistory";
            btnEditHistory.Size = new Size(120, 36);
            btnEditHistory.TabIndex = 1;
            btnEditHistory.Text = "Edit History";
            btnEditHistory.UseVisualStyleBackColor = true;
            btnEditHistory.Click += btnEditHistory_Click;
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            Controls.Add(tblLayout);
            Name = "PatientRecordControl";
            Size = new Size(779, 592);
            tblHeader.ResumeLayout(false);
            tblHeader.PerformLayout();
            tblLayout.ResumeLayout(false);
            tableLayoutPanel1.ResumeLayout(false);
            tbPatientRecord.ResumeLayout(false);
            tabVitals.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvVitals).EndInit();
            tabConsultations.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvConsultations).EndInit();
            tabPrescriptions.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dgvPrescriptions).EndInit();
            tabMedicalHistory.ResumeLayout(false);
            tableLayoutPanel2.ResumeLayout(false);
            tableLayoutPanel3.ResumeLayout(false);
            tableLayoutPanel3.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Label lblPatientInfo;
        private TableLayoutPanel tblHeader;
        private ComboBox cboPatient;
        private Label lblPatient;
        private Label lblPatientName;
        private Label labelMeta;
        private Label lblAllergies;
        private Label lblMeta;
        private Label lblAllergy;
        private TableLayoutPanel tblLayout;
        private TableLayoutPanel tableLayoutPanel1;
        private TabControl tbPatientRecord;
        private TabPage tabVitals;
        private DataGridView dgvVitals;
        private TabPage tabConsultations;
        private DataGridView dgvConsultations;
        private TabPage tabPrescriptions;
        private DataGridView dgvPrescriptions;
        private TabPage tabMedicalHistory;
        private TableLayoutPanel tableLayoutPanel2;
        private TableLayoutPanel tableLayoutPanel3;
        private TextBox txtHxMeds;
        private Label lblCurrMed;
        private TextBox txtHxFamily;
        private Label lblFamHis;
        private Label lblSurgery;
        private Label lblConditions;
        private TextBox txtHxAllergies;
        private Label label2;
        private TextBox txtHxConditions;
        private TextBox txtHxSurgeries;
        private Button btnEditHistory;
        private Button btnPrint;
    }
}
